if SERVER then AddCSLuaFile() end

--
-- Episode One Achievements list
--

EP1_ACH_LIST = {
	"ACHIEVEMENT_EVENT_EP1_BEAT_MAINELEVATOR",
	"ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_END",
	"ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_NOSTALKERKILLS",
	"ACHIEVEMENT_EVENT_EP1_BEAT_GARAGEELEVATORSTANDOFF",
	"ACHIEVEMENT_EVENT_EP1_BEAT_HOSPITALATTICGUNSHIP",
	"ACHIEVEMENT_EVENT_EP1_BEAT_CITIZENESCORT_NOCITIZENDEATHS_END",
	"ACHIEVEMENT_EVENT_EP1_BEAT_GAME",
	
	
	"ACHIEVEMENT_EVENT_EP1_KILL_ANTLIONS_WITHCARS",
	"ACHIEVEMENT_EVENT_EP1_KILL_ENEMIES_WITHSNIPERALYX",
	"ACHIEVEMENT_EVENT_EP1_BEAT_GAME_ONEBULLET",
	"ACHIEVEMENT_EVENT_EP1_KILL_ZOMBIES_WITHFLARES",
	"ACHIEVEMENT_EVENT_EP1_BEAT_GAME_ONLYCROWBAR",
	
}

EP1_ACH_LIST_TITLE = {
	["ACHIEVEMENT_EVENT_EP1_BEAT_MAINELEVATOR"] = "Watch Your Head!",
	["ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_END"] = "Containment",
	["ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_NOSTALKERKILLS"] = "Pacifist",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GARAGEELEVATORSTANDOFF"] = "Elevator Action",
	["ACHIEVEMENT_EVENT_EP1_BEAT_HOSPITALATTICGUNSHIP"] = "Attica!",
	["ACHIEVEMENT_EVENT_EP1_BEAT_CITIZENESCORT_NOCITIZENDEATHS_END"] = "Citizen Escort",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GAME"] = "Escape From City 17",
	
	["ACHIEVEMENT_EVENT_EP1_KILL_ANTLIONS_WITHCARS"] = "Car Crusher",
	["ACHIEVEMENT_EVENT_EP1_KILL_ENEMIES_WITHSNIPERALYX"] = "Live Bait",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GAME_ONEBULLET"] = "The One Free Bullet",
	["ACHIEVEMENT_EVENT_EP1_KILL_ZOMBIES_WITHFLARES"] = "Zombie-que",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GAME_ONLYCROWBAR"] = "The One True Freeman",
}

EP1_ACH_LIST_TEXT = {
	["ACHIEVEMENT_EVENT_EP1_BEAT_MAINELEVATOR"] = "Make it to the bottom of the Citadel's main elevator shaft in one piece.",
	["ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_END"] = "Contain the citadel core.",
	["ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_NOSTALKERKILLS"] = "Contain the Citadel core without killing any stalkers.",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GARAGEELEVATORSTANDOFF"] = "Survive long enough to get on the parking garage elevator.",
	["ACHIEVEMENT_EVENT_EP1_BEAT_HOSPITALATTICGUNSHIP"] = "Destroy the gunship in the hospital attic.",
	["ACHIEVEMENT_EVENT_EP1_BEAT_CITIZENESCORT_NOCITIZENDEATHS_END"] = "Don't let any citizens die when escorting them to the escape train",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GAME"] = "Escape City 17 with Alyx.",
	
	["ACHIEVEMENT_EVENT_EP1_KILL_ANTLIONS_WITHCARS"] = "Use the cars to squash 15 antlions in Episode One.",
	["ACHIEVEMENT_EVENT_EP1_KILL_ENEMIES_WITHSNIPERALYX"] = "Help Alyx snipe 30 enemies in Episode One.",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GAME_ONEBULLET"] = "Finish the game firing exactly one bullet. Grenade, crowbar, rocket, and Gravity Gun kills are okay!",
	["ACHIEVEMENT_EVENT_EP1_KILL_ZOMBIES_WITHFLARES"] = "Use flares to light 15 zombies on fire.",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GAME_ONLYCROWBAR"] = "Beat the game only using a crowbar",
}

EP1_ACH_LIST_MAT = {
	["ACHIEVEMENT_EVENT_EP1_BEAT_MAINELEVATOR"] = "vgui/achievements/ep1_beat_mainelevator",
	["ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_END"] = "vgui/achievements/ep1_beat_citadelcore",
	["ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_NOSTALKERKILLS"] = "vgui/achievements/ep1_beat_citadelcore_nostalkerkills",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GARAGEELEVATORSTANDOFF"] = "vgui/achievements/ep1_beat_garageelevatorstandoff",
	["ACHIEVEMENT_EVENT_EP1_BEAT_HOSPITALATTICGUNSHIP"] = "vgui/achievements/ep1_beat_hospitalatticgunship",
	["ACHIEVEMENT_EVENT_EP1_BEAT_CITIZENESCORT_NOCITIZENDEATHS_END"] = "vgui/achievements/ep1_beat_citizenescort_nocitizendeaths",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GAME"] = "vgui/achievements/ep1_beat_game",
	
	["ACHIEVEMENT_EVENT_EP1_KILL_ANTLIONS_WITHCARS"] = "vgui/achievements/ep1_kill_antlions_withcars",
	["ACHIEVEMENT_EVENT_EP1_KILL_ENEMIES_WITHSNIPERALYX"] = "vgui/achievements/ep1_kill_enemies_withsniperalyx",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GAME_ONEBULLET"] = "vgui/achievements/ep1_beat_game_onebullet",
	["ACHIEVEMENT_EVENT_EP1_KILL_ZOMBIES_WITHFLARES"] = "vgui/achievements/epx_kill_zombies_withflares",
	["ACHIEVEMENT_EVENT_EP1_BEAT_GAME_ONLYCROWBAR"] = "vgui/achievements/hl2_get_crowbar",
}

-- PART TWO EPISODE ONE ACHIEVEMENTS

EP1_P2_ACH_LIST = {
	

}

EP1_P2_ACH_LIST_TITLE = {
	

}

EP1_P2_ACH_LIST_TEXT = {
	
}

EP1_P2_ACH_LIST_MAT = {
	
}

Hl2c.EP1_ACH_LIST = {
	[1]="ACHIEVEMENT_EVENT_EP1_BEAT_MAINELEVATOR",
	[2]="ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_END",
	[3]="ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_NOSTALKERKILLS",
	[4]="ACHIEVEMENT_EVENT_EP1_BEAT_GARAGEELEVATORSTANDOFF",
	[5]="ACHIEVEMENT_EVENT_EP1_BEAT_HOSPITALATTICGUNSHIP",
	[6]="ACHIEVEMENT_EVENT_EP1_BEAT_CITIZENESCORT_NOCITIZENDEATHS_END",
	[7]="ACHIEVEMENT_EVENT_EP1_BEAT_GAME",
	
	[8]="ACHIEVEMENT_EVENT_EP1_KILL_ANTLIONS_WITHCARS",
	[9]="ACHIEVEMENT_EVENT_EP1_KILL_ENEMIES_WITHSNIPERALYX",
	[10]="ACHIEVEMENT_EVENT_EP1_BEAT_GAME_ONEBULLET",
	[11]="ACHIEVEMENT_EVENT_EP1_KILL_ZOMBIES_WITHFLARES",
	[12]="ACHIEVEMENT_EVENT_EP1_BEAT_GAME_ONLYCROWBAR",
	}