if SERVER then AddCSLuaFile() end
--
-- Episode Two Achievments List
--

EP2_ACH_LIST = {
	"ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONINVASION",
	"ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONGUARDS",
	"ACHIEVEMENT_EVENT_EP2_BEAT_HUNTERAMBUSH",
	"ACHIEVEMENT_EVENT_EP2_KILL_CHOPPER_NOMISSES_END",
	"ACHIEVEMENT_EVENT_EP2_KILL_COMBINECANNON",
	"ACHIEVEMENT_EVENT_EP2_BEAT_RACEWITHDOG",
	"ACHIEVEMENT_EVENT_EP2_BEAT_ROCKETCACHEPUZZLE",
	"ACHIEVEMENT_EVENT_EP2_BEAT_WHITEFORESTINN",
	"ACHIEVEMENT_EVENT_EP2_PUT_ITEMINROCKET",
	"ACHIEVEMENT_EVENT_EP2_BEAT_MISSILESILO2",
	"ACHIEVEMENT_EVENT_EP2_BEAT_GAME",
	"ACHIEVEMENT_EVENT_EP2_BEAT_OUTLAND12_NOBUILDINGSDESTROYED",
	
	
	"ACHIEVEMENT_EVENT_EP2_KILL_POISONANTLION",
	"ACHIEVEMENT_EVENT_EP2_KILL_ALLGRUBS",
	"ACHIEVEMENT_EVENT_EP2_KILL_ENEMIES_WITHCAR",
	"ACHIEVEMENT_EVENT_EP2_KILL_HUNTER_WITHFLECHETTES",
	"ACHIEVEMENT_EVENT_HLX_KILL_ENEMY_WITHHOPPERMINE",
	"ACHIEVEMENT_EVENT_HLX_KILL_ENEMIES_WITHPHYSICS",
	"ACHIEVEMENT_EVENT_EP2_FIND_ALLRADARCACHES",
	"ACHIEVEMENT_EVENT_EP2_BREAK_ALLWEBS",
	"ACHIEVEMENT_EVENT_EP2_BEAT_GAME_ONLYCROWBAR",
	"ACHIEVEMENT_EVENT_EP2_KILL_GRAVEROBBER",
	"ACHIEVEMENT_EVENT_HLX_KILL_SOLDIER_WITHHISGRENADE",
}


EP2_ACH_LIST_TITLE = {
	["ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONINVASION"] = "Into the Breach",
	["ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONGUARDS"] = "Twofer",
	["ACHIEVEMENT_EVENT_EP2_BEAT_HUNTERAMBUSH"] = "Meet the Hunters",
	["ACHIEVEMENT_EVENT_EP2_KILL_CHOPPER_NOMISSES_END"] = "Puttin' On a Clinic",
	["ACHIEVEMENT_EVENT_EP2_KILL_COMBINECANNON"] = "Gunishment!",
	["ACHIEVEMENT_EVENT_EP2_BEAT_RACEWITHDOG"] = "Pedal to the Metal",
	["ACHIEVEMENT_EVENT_EP2_BEAT_ROCKETCACHEPUZZLE"] = "Gordon Propelled Rocket",
	["ACHIEVEMENT_EVENT_EP2_BEAT_WHITEFORESTINN"] = "Quiet Mountain Getaway",
	["ACHIEVEMENT_EVENT_EP2_PUT_ITEMINROCKET"] = "Little Rocket Man",
	["ACHIEVEMENT_EVENT_EP2_BEAT_MISSILESILO2"] = "Secondary Silo Secured",
	["ACHIEVEMENT_EVENT_EP2_BEAT_GAME"] = "Defense of the Armament",
	["ACHIEVEMENT_EVENT_EP2_BEAT_OUTLAND12_NOBUILDINGSDESTROYED"] = "Neighborhood Watch",
	
	
	["ACHIEVEMENT_EVENT_EP2_KILL_POISONANTLION"] = "Acid Reflex",
	["ACHIEVEMENT_EVENT_EP2_KILL_ALLGRUBS"] = "Get Some Grub",
	["ACHIEVEMENT_EVENT_EP2_KILL_ENEMIES_WITHCAR"] = "Hit and Run",
	["ACHIEVEMENT_EVENT_EP2_KILL_HUNTER_WITHFLECHETTES"] = "Payback",
	["ACHIEVEMENT_EVENT_HLX_KILL_ENEMY_WITHHOPPERMINE"] = "Deadly Harvest",
	["ACHIEVEMENT_EVENT_HLX_KILL_ENEMIES_WITHPHYSICS"] = "Bone Breaker",
	["ACHIEVEMENT_EVENT_EP2_FIND_ALLRADARCACHES"] = "Cache Checker",
	["ACHIEVEMENT_EVENT_EP2_BREAK_ALLWEBS"] = "Pinata Party",
	["ACHIEVEMENT_EVENT_EP2_BEAT_GAME_ONLYCROWBAR"] = "The One True Freeman",
	["ACHIEVEMENT_EVENT_EP2_KILL_GRAVEROBBER"] = "Grave Robber",
	["ACHIEVEMENT_EVENT_HLX_KILL_SOLDIER_WITHHISGRENADE"] = "Hot Potat0wned",
}

EP2_ACH_LIST_TEXT = {
	["ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONINVASION"] = "Help Griggs and Sheckley hold off the antlion invasion inside the mine shaft.",
	["ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONGUARDS"] = "Defeat both antlion guards outside the White Forest",
	["ACHIEVEMENT_EVENT_EP2_BEAT_HUNTERAMBUSH"] = "Survive the Hunter ambush at the radio tower.",
	["ACHIEVEMENT_EVENT_EP2_KILL_CHOPPER_NOMISSES_END"] = "End of the chopper arena battle.",
	["ACHIEVEMENT_EVENT_EP2_KILL_COMBINECANNON"] = "Destroy the Combine Cannon in the junkyard.",
	["ACHIEVEMENT_EVENT_EP2_BEAT_RACEWITHDOG"] = "Beat DOG in the race to the White Forest.",
	["ACHIEVEMENT_EVENT_EP2_BEAT_ROCKETCACHEPUZZLE"] = "Unlock the Rocket Launcher lambda cache in chapter Under The Radar.",
	["ACHIEVEMENT_EVENT_EP2_BEAT_WHITEFORESTINN"] = "Survive the invasion at White Forest Inn",
	["ACHIEVEMENT_EVENT_EP2_PUT_ITEMINROCKET"] = "Send the garden gnome into space.",
	["ACHIEVEMENT_EVENT_EP2_BEAT_MISSILESILO2"] = "Secure the launch doors on missile silo 2.",
	["ACHIEVEMENT_EVENT_EP2_BEAT_GAME"] = "Save the missile silo from the Combine offensive.",
	["ACHIEVEMENT_EVENT_EP2_BEAT_OUTLAND12_NOBUILDINGSDESTROYED"] = "Save the missile silo without losing any buildings.",
	
	
	["ACHIEVEMENT_EVENT_EP2_KILL_POISONANTLION"] = "Kill an acid antlion worker.",
	["ACHIEVEMENT_EVENT_EP2_KILL_ALLGRUBS"] = "Squish every antlion grub in Episode Two.",
	["ACHIEVEMENT_EVENT_EP2_KILL_ENEMIES_WITHCAR"] = "Run over 20 enemies with the car in Episode Two.",
	["ACHIEVEMENT_EVENT_EP2_KILL_HUNTER_WITHFLECHETTES"] = "Kill a Hunter with its own flechettes.",
	["ACHIEVEMENT_EVENT_HLX_KILL_ENEMY_WITHHOPPERMINE"] = "Kill an enemy by planting a hopper mine.",
	["ACHIEVEMENT_EVENT_HLX_KILL_ENEMIES_WITHPHYSICS"] = "Kill 30 enemies with thrown physics objects.",
	["ACHIEVEMENT_EVENT_EP2_FIND_ALLRADARCACHES"] = "Find every radar cache in chapter Under The Radar.",
	["ACHIEVEMENT_EVENT_EP2_BREAK_ALLWEBS"] = "Find and break every web cache in Episode Two.",
	["ACHIEVEMENT_EVENT_EP2_BEAT_GAME_ONLYCROWBAR"] = "Beat the game only using a crowbar",
	["ACHIEVEMENT_EVENT_EP2_KILL_GRAVEROBBER"] = "Steal a Zombine's grenade.",
	["ACHIEVEMENT_EVENT_HLX_KILL_SOLDIER_WITHHISGRENADE"] = "Kill a Combine soldier with his own grenade.",
}

EP2_ACH_LIST_MAT = {
	["ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONINVASION"] = "vgui/achievements/ep2_beat_antlioninvasion",
	["ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONGUARDS"] = "vgui/achievements/ep2_beat_antlionguards",
	["ACHIEVEMENT_EVENT_EP2_BEAT_HUNTERAMBUSH"] = "vgui/achievements/ep2_beat_hunterambush",
	["ACHIEVEMENT_EVENT_EP2_KILL_CHOPPER_NOMISSES_END"] = "vgui/achievements/ep2_kill_chopper_nomisses",
	["ACHIEVEMENT_EVENT_EP2_KILL_COMBINECANNON"] = "vgui/achievements/ep2_kill_combinecannon",
	["ACHIEVEMENT_EVENT_EP2_BEAT_RACEWITHDOG"] = "vgui/achievements/ep2_beat_racewithdog",
	["ACHIEVEMENT_EVENT_EP2_BEAT_ROCKETCACHEPUZZLE"] = "vgui/achievements/ep2_beat_rocketcachepuzzle",
	["ACHIEVEMENT_EVENT_EP2_BEAT_WHITEFORESTINN"] = "vgui/achievements/ep2_beat_whiteforestinn",
	["ACHIEVEMENT_EVENT_EP2_PUT_ITEMINROCKET"] = "vgui/achievements/ep2_put_iteminrocket",
	["ACHIEVEMENT_EVENT_EP2_BEAT_MISSILESILO2"] = "vgui/achievements/ep2_beat_missilesilo2",
	["ACHIEVEMENT_EVENT_EP2_BEAT_GAME"] = "vgui/achievements/ep2_beat_game",
	["ACHIEVEMENT_EVENT_EP2_BEAT_OUTLAND12_NOBUILDINGSDESTROYED"] = "vgui/achievements/ep2_beat_outland12_nobuildingsdestroyed",
	
	["ACHIEVEMENT_EVENT_EP2_KILL_POISONANTLION"] = "vgui/achievements/ep2_kill_poisonantlion",
	["ACHIEVEMENT_EVENT_EP2_KILL_ALLGRUBS"] = "vgui/achievements/ep2_kill_allgrubs",
	["ACHIEVEMENT_EVENT_EP2_KILL_ENEMIES_WITHCAR"] = "vgui/achievements/ep2_kill_enemies_withcar",
	["ACHIEVEMENT_EVENT_EP2_KILL_HUNTER_WITHFLECHETTES"] = "vgui/achievements/ep2_kill_hunter_withflechettes",
	["ACHIEVEMENT_EVENT_HLX_KILL_ENEMY_WITHHOPPERMINE"] = "vgui/achievements/hlx_kill_enemy_withhoppermine",
	["ACHIEVEMENT_EVENT_HLX_KILL_ENEMIES_WITHPHYSICS"] = "vgui/achievements/hlx_kill_enemies_withphysics",
	["ACHIEVEMENT_EVENT_EP2_FIND_ALLRADARCACHES"] = "vgui/achievements/ep2_find_allradarcaches",
	["ACHIEVEMENT_EVENT_EP2_BREAK_ALLWEBS"] = "vgui/achievements/ep2_break_allwebs",
	["ACHIEVEMENT_EVENT_EP2_BEAT_GAME_ONLYCROWBAR"] = "vgui/achievements/hl2_get_crowbar",
	["ACHIEVEMENT_EVENT_EP2_KILL_GRAVEROBBER"] = "vgui/achievements/epx_get_zombinegrenade",
	["ACHIEVEMENT_EVENT_HLX_KILL_SOLDIER_WITHHISGRENADE"] = "vgui/achievements/hlx_kill_soldier_withhisgrenade",
}

EP2_P2_ACH_LIST = {
	
}

EP2_P2_ACH_LIST_TITLE = {
	
}

EP2_P2_ACH_LIST_TEXT = {
	
}

EP2_P2_ACH_LIST_MAT = {
	
}


Hl2c.EP2_ACH_LIST = {
	[1]="ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONINVASION",
	[2]="ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONGUARDS",
	[3]="ACHIEVEMENT_EVENT_EP2_BEAT_HUNTERAMBUSH",
	[4]="ACHIEVEMENT_EVENT_EP2_KILL_CHOPPER_NOMISSES_END",
	[5]="ACHIEVEMENT_EVENT_EP2_KILL_COMBINECANNON",
	[6]="ACHIEVEMENT_EVENT_EP2_BEAT_RACEWITHDOG",
	[7]="ACHIEVEMENT_EVENT_EP2_BEAT_ROCKETCACHEPUZZLE",
	[8]="ACHIEVEMENT_EVENT_EP2_BEAT_WHITEFORESTINN",
	[9]="ACHIEVEMENT_EVENT_EP2_PUT_ITEMINROCKET",
	[10]="ACHIEVEMENT_EVENT_EP2_BEAT_MISSILESILO2",
	[11]="ACHIEVEMENT_EVENT_EP2_BEAT_GAME",
	[12]="ACHIEVEMENT_EVENT_EP2_BEAT_OUTLAND12_NOBUILDINGSDESTROYED",
	
	[13]="ACHIEVEMENT_EVENT_EP2_KILL_POISONANTLION",
	[14]="ACHIEVEMENT_EVENT_EP2_KILL_ALLGRUBS",
	[15]="ACHIEVEMENT_EVENT_EP2_KILL_ENEMIES_WITHCAR",
	[16]="ACHIEVEMENT_EVENT_EP2_KILL_HUNTER_WITHFLECHETTES",
	[17]="ACHIEVEMENT_EVENT_HLX_KILL_ENEMY_WITHHOPPERMINE",
	[18]="ACHIEVEMENT_EVENT_HLX_KILL_ENEMIES_WITHPHYSICS",
	[19]="ACHIEVEMENT_EVENT_EP2_FIND_ALLRADARCACHES",
	[20]="ACHIEVEMENT_EVENT_EP2_BREAK_ALLWEBS",
	[21]="ACHIEVEMENT_EVENT_EP2_BEAT_GAME_ONLYCROWBAR",
	[22]="ACHIEVEMENT_EVENT_EP2_KILL_GRAVEROBBER",
	[23]="ACHIEVEMENT_EVENT_HLX_KILL_SOLDIER_WITHHISGRENADE",
	
}