if SERVER then AddCSLuaFile() end
--
-- General Achievements list
--

GEN_ACH_LIST = {
	"ACHIEVEMENT_EVENT_GEN_BEAT_ALLHL2",
	"ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP1",
	"ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP2",
	"ACHIEVEMENT_EVENT_GEN_KILL_100ANTLIONS",
	"ACHIEVEMENT_EVENT_GEN_KILL_1000ANTLIONS",
	"ACHIEVEMENT_EVENT_GEN_KILL_10000ANTLIONS",
	"ACHIEVEMENT_EVENT_GEN_KILL_100000ANTLIONS",
	"ACHIEVEMENT_EVENT_GEN_KILL_100ZOMBIES",
	"ACHIEVEMENT_EVENT_GEN_KILL_1000ZOMBIES",
	"ACHIEVEMENT_EVENT_GEN_KILL_10000ZOMBIES",
	"ACHIEVEMENT_EVENT_GEN_KILL_100000ZOMBIES",
	"ACHIEVEMENT_EVENT_GEN_KILL_100COMBINES",
	"ACHIEVEMENT_EVENT_GEN_KILL_1000COMBINES",
	"ACHIEVEMENT_EVENT_GEN_KILL_10000COMBINES",
	"ACHIEVEMENT_EVENT_GEN_KILL_100000COMBINES",
	"ACHIEVEMENT_EVENT_GEN_KILL_100REBELS",
	"ACHIEVEMENT_EVENT_GEN_KILL_1000REBELS",
	"ACHIEVEMENT_EVENT_GEN_KILL_10000REBELS",
	"ACHIEVEMENT_EVENT_GEN_KILL_100000REBELS",
	"ACHIEVEMENT_EVENT_GEN_KILL_100VORTIGAUNTS",
	"ACHIEVEMENT_EVENT_GEN_KILL_1000VORTIGAUNTS",
	"ACHIEVEMENT_EVENT_GEN_KILL_10000VORTIGAUNTS",
	"ACHIEVEMENT_EVENT_GEN_KILL_100000VORTIGAUNTS",
	"ACHIEVEMENT_EVENT_GEN_KILL_100HEADCRABS",
	"ACHIEVEMENT_EVENT_GEN_KILL_1000HEADCRABS",
	"ACHIEVEMENT_EVENT_GEN_KILL_10000HEADCRABS",
	"ACHIEVEMENT_EVENT_GEN_KILL_100000HEADCRABS",
	
	
	"ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP3",
	"ACHIEVEMENT_EVENT_GEN_BEAT_ALLCD",
	"ACHIEVEMENT_EVENT_GEN_BEAT_ALLMETA",
	"ACHIEVEMENT_EVENT_GEN_EVENT_EP2_OPEN",
	
	"ACHIEVEMENT_EVENT_GEN_LOOT_100S3",
	"ACHIEVEMENT_EVENT_GEN_LOOT_LEGENDARY",
	"ACHIEVEMENT_EVENT_GEN_LOOT_PLAN",
	
	"ACHIEVEMENT_EVENT_GEN_LOOT_LOOT10",
	"ACHIEVEMENT_EVENT_GEN_LOOT_LOOT100",
	"ACHIEVEMENT_EVENT_GEN_LOOT_LOOT1000",
	"ACHIEVEMENT_EVENT_GEN_LOOT_LOOT100000",
	"ACHIEVEMENT_EVENT_GEN_LOOT_LOOT1000000",
	"ACHIEVEMENT_EVENT_GEN_LOOT_LOOT10000000",
	
	
	"ACHIEVEMENT_EVENT_GEN_EVENT_LOVE_4EVER",
	"ACHIEVEMENT_EVENT_GEN_EVENT_FIND_EGGS",
	"ACHIEVEMENT_EVENT_GEN_EVENT_HALLOWEEN_2016",
	"ACHIEVEMENT_EVENT_GEN_KILL_HEADLESS_BOSS",
	"ACHIEVEMENT_EVENT_GEN_EVENT_CHRISTMAS_2016",
	"ACHIEVEMENT_EVENT_GEN_SAVE_SANTA",
	"ACHIEVEMENT_EVENT_GEN_EVENT_NEWYEAR_2017",
	"ACHIEVEMENT_EVENT_GEN_EVENT_LOVE_2017",
	"ACHIEVEMENT_EVENT_GEN_EVENT_EASTER_2017",
}

GEN_ACH_LIST_TITLE = {
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLHL2"] = "Half - Life 2",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP1"] = "Episode One",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP2"] = "Episode Two",
	["ACHIEVEMENT_EVENT_GEN_KILL_100ANTLIONS"] = "Antlion slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000ANTLIONS"] = "Antlion slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000ANTLIONS"] = "Antlion slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000ANTLIONS"] = "Antlion slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_100ZOMBIES"] = "Zombie slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000ZOMBIES"] = "Zombie slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000ZOMBIES"] = "Zombie slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000ZOMBIES"] = "Zombie slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_100COMBINES"] = "Combine slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000COMBINES"] = "Combine slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000COMBINES"] = "Combine slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000COMBINES"] = "Combine slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_100REBELS"] = "Rebel slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000REBELS"] = "Rebel slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000REBELS"] = "Rebel slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000REBELS"] = "Rebel slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_100VORTIGAUNTS"] = "Vortigaunt slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000VORTIGAUNTS"] = "Vortigaunt slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000VORTIGAUNTS"] = "Vortigaunt slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000VORTIGAUNTS"] = "Vortigaunt slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_100HEADCRABS"] = "Headcrab slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000HEADCRABS"] = "Headcrab slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000HEADCRABS"] = "Headcrab slayer",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000HEADCRABS"] = "Headcrab slayer",
	
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP3"] = "Episode Three",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLCD"] = "Combine Destinty",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLMETA"] = "Metastasis:Minerva",
	["ACHIEVEMENT_EVENT_GEN_EVENT_EP2_OPEN"] = "Episode Two Opening",
	
	["ACHIEVEMENT_EVENT_GEN_LOOT_100S3"] = "Season 3 100th",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LEGENDARY"] ="Lucky loot",
	["ACHIEVEMENT_EVENT_GEN_LOOT_PLAN"] = "Engineer loot",
	
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT10"]="Loot 10",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT100"]="Loot 1 hundred",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT1000"]="Loot 1 thousand",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT100000"]="Loot 10 thousand",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT1000000"]="Loot 100 thousand",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT10000000"]="Loot 1 million",
	
	
	
	["ACHIEVEMENT_EVENT_GEN_EVENT_LOVE_4EVER"] = "Love through dead",
	["ACHIEVEMENT_EVENT_GEN_EVENT_FIND_EGGS"] = "Egg Hunt",
	["ACHIEVEMENT_EVENT_GEN_EVENT_HALLOWEEN_2016"] = "Halloween Event 2016",
	["ACHIEVEMENT_EVENT_GEN_KILL_HEADLESS_BOSS"] = "No more heads!",
	["ACHIEVEMENT_EVENT_GEN_EVENT_CHRISTMAS_2016"] = "Christmas Event 2016",
	["ACHIEVEMENT_EVENT_GEN_SAVE_SANTA"] = "No more Coal",
	["ACHIEVEMENT_EVENT_GEN_EVENT_NEWYEAR_2017"] = "Happy New Year 2017",
	["ACHIEVEMENT_EVENT_GEN_EVENT_LOVE_2017"] = "Valentine's Day Event 2016",
	["ACHIEVEMENT_EVENT_GEN_EVENT_EASTER_2017"] = "Easter Event 2017",
}

GEN_ACH_LIST_TEXT = {
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLHL2"] = "Get all Half - Life 2 achievements.",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP1"] = "Get all Episode One achievements.",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP2"] = "Get all Episode Two achievements.",
	["ACHIEVEMENT_EVENT_GEN_KILL_100ANTLIONS"] = "Kill 100 antlions",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000ANTLIONS"] = "Kill 1 000 antlions",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000ANTLIONS"] = "Kill 10 000 antlions",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000ANTLIONS"] = "Kill 100 000 antlions",
	["ACHIEVEMENT_EVENT_GEN_KILL_100ZOMBIES"] = "Kill 100 zombies",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000ZOMBIES"] = "Kill 1 000 zombies",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000ZOMBIES"] = "Kill 10 000 zombies",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000ZOMBIES"] = "Kill 100 000 zombies",
	["ACHIEVEMENT_EVENT_GEN_KILL_100COMBINES"] = "Kill 100 combines",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000COMBINES"] = "Kill 1 000 combines",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000COMBINES"] = "Kill 10 000 combines",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000COMBINES"] = "Kill 100 000 combines",
	["ACHIEVEMENT_EVENT_GEN_KILL_100REBELS"] = "Kill 100 rebels",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000REBELS"] = "Kill 1 000 rebels",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000REBELS"] = "Kill 10 000 rebels",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000REBELS"] = "Kill 100 000 rebels",
	["ACHIEVEMENT_EVENT_GEN_KILL_100VORTIGAUNTS"] = "Kill 100 vortigaunts",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000VORTIGAUNTS"] = "Kill 1 000 vortigaunts",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000VORTIGAUNTS"] = "Kill 10 000 vortigaunts",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000VORTIGAUNTS"] = "Kill 100 000 vortigaunts",
	["ACHIEVEMENT_EVENT_GEN_KILL_100HEADCRABS"] = "Kill 100 headcrabs",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000HEADCRABS"] = "Kill 1 000 headcrabs",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000HEADCRABS"] = "Kill 10 000 headcrabs",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000HEADCRABS"] = "Kill 100 000 headcrabs",
	
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP3"] = "Get All Episode Three Achievements",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLCD"] = "Get All Combine Destinty Achievements",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLMETA"] = "Get All Metastasis:Minerva Achievements",
	["ACHIEVEMENT_EVENT_GEN_EVENT_EP2_OPEN"] = "Be at Episode Two opening celebration and stop combine",
	
	
	["ACHIEVEMENT_EVENT_GEN_LOOT_100S3"] = "Loot 100 in Monster Level 7 or higher",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LEGENDARY"] ="Loot a legendary",
	["ACHIEVEMENT_EVENT_GEN_LOOT_PLAN"] = "Loot a plan",
	
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT10"]="Loot 10 crate",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT100"]="Loot 100 crate",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT1000"]="Loot 1.000 crate",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT100000"]="Loot 10.000 crate",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT1000000"]="Loot 100.000 crate",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT10000000"]="Loo 1.000.000 crate",
	
	
	["ACHIEVEMENT_EVENT_GEN_EVENT_LOVE_4EVER"] = "Kiss someone and dont die on that map",
	["ACHIEVEMENT_EVENT_GEN_EVENT_FIND_EGGS"] = "Find all eggs during Easter event",
	["ACHIEVEMENT_EVENT_GEN_EVENT_HALLOWEEN_2016"] = "Be at the Halloween event in 2016",
	["ACHIEVEMENT_EVENT_GEN_KILL_HEADLESS_BOSS"] = "Kill the Headless Horseman during Halloween",
	["ACHIEVEMENT_EVENT_GEN_EVENT_CHRISTMAS_2016"] = "Be at the Christmas event in 2016",
	["ACHIEVEMENT_EVENT_GEN_SAVE_SANTA"] = "Save the Christmas during Christmas",
	["ACHIEVEMENT_EVENT_GEN_EVENT_NEWYEAR_2017"] = "Be at the celebration of the new Year 2017",
	["ACHIEVEMENT_EVENT_GEN_EVENT_LOVE_2017"] = "Be at the Valentine's day event in 2017",
	["ACHIEVEMENT_EVENT_GEN_EVENT_EASTER_2017"] = "Be at the Easter event in 2017",
	
}

GEN_ACH_LIST_MAT = {
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLHL2"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP1"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP2"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_KILL_100ANTLIONS"] = "vgui/achievements/ep2_kill_poisonantlion",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000ANTLIONS"] = "vgui/achievements/ep2_kill_poisonantlion",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000ANTLIONS"] = "vgui/achievements/ep2_kill_poisonantlion",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000ANTLIONS"] = "vgui/achievements/ep2_kill_poisonantlion",
	["ACHIEVEMENT_EVENT_GEN_KILL_100ZOMBIES"] = "vgui/achievements/epx_get_zombinegrenade",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000ZOMBIES"] = "vgui/achievements/epx_get_zombinegrenade",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000ZOMBIES"] = "vgui/achievements/epx_get_zombinegrenade",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000ZOMBIES"] = "vgui/achievements/epx_get_zombinegrenade",
	["ACHIEVEMENT_EVENT_GEN_KILL_100COMBINES"] = "vgui/achievements/hlx_kill_soldier_withhisgrenade",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000COMBINES"] = "vgui/achievements/hlx_kill_soldier_withhisgrenade",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000COMBINES"] = "vgui/achievements/hlx_kill_soldier_withhisgrenade",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000COMBINES"] = "vgui/achievements/hlx_kill_soldier_withhisgrenade",
	["ACHIEVEMENT_EVENT_GEN_KILL_100REBELS"] = "vgui/achievements/hl2_beat_plazastandoff",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000REBELS"] = "vgui/achievements/hl2_beat_plazastandoff",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000REBELS"] = "vgui/achievements/hl2_beat_plazastandoff",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000REBELS"] = "vgui/achievements/hl2_beat_plazastandoff",
	["ACHIEVEMENT_EVENT_GEN_KILL_100VORTIGAUNTS"] = "vgui/achievements/hl2_find_vortigauntcave",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000VORTIGAUNTS"] = "vgui/achievements/hl2_find_vortigauntcave",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000VORTIGAUNTS"] = "vgui/achievements/hl2_find_vortigauntcave",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000VORTIGAUNTS"] = "vgui/achievements/hl2_find_vortigauntcave",
	["ACHIEVEMENT_EVENT_GEN_KILL_100HEADCRABS"] = "vgui/achievements/hl2_get_crowbar",
	["ACHIEVEMENT_EVENT_GEN_KILL_1000HEADCRABS"] = "vgui/achievements/hl2_get_crowbar",
	["ACHIEVEMENT_EVENT_GEN_KILL_10000HEADCRABS"] = "vgui/achievements/hl2_get_crowbar",
	["ACHIEVEMENT_EVENT_GEN_KILL_100000HEADCRABS"] = "vgui/achievements/hl2_get_crowbar",
	
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP3"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLCD"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_BEAT_ALLMETA"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_EVENT_EP2_OPEN"] = "vgui/achievements/hl2_find_alllambdas",
	
	["ACHIEVEMENT_EVENT_GEN_LOOT_100S3"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LEGENDARY"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_LOOT_PLAN"] = "vgui/achievements/hl2_find_alllambdas",
	
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT10"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT100"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT1000"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT100000"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT1000000"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_LOOT_LOOT10000000"] = "vgui/achievements/hl2_find_alllambdas",
	
	
	["ACHIEVEMENT_EVENT_GEN_EVENT_LOVE_4EVER"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_EVENT_FIND_EGGS"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_EVENT_HALLOWEEN_2016"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_KILL_HEADLESS_BOSS"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_EVENT_CHRISTMAS_2016"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_SAVE_SANTA"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_EVENT_NEWYEAR_2017"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_EVENT_LOVE_2017"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_GEN_EVENT_EASTER_2017"] = "vgui/achievements/hl2_find_alllambdas",
}
--
-- Part 2 General Achievements
--





Hl2c.GEN_ACH_LIST = {
	[1]="ACHIEVEMENT_EVENT_GEN_BEAT_ALLHL2",
	[2]="ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP1",
	[3]="ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP2",
	[4]="ACHIEVEMENT_EVENT_GEN_KILL_100ANTLIONS",
	[5]="ACHIEVEMENT_EVENT_GEN_KILL_1000ANTLIONS",
	[6]="ACHIEVEMENT_EVENT_GEN_KILL_10000ANTLIONS",
	[7]="ACHIEVEMENT_EVENT_GEN_KILL_100000ANTLIONS",
	[8]="ACHIEVEMENT_EVENT_GEN_KILL_100ZOMBIES",
	[9]="ACHIEVEMENT_EVENT_GEN_KILL_1000ZOMBIES",
	[10]="ACHIEVEMENT_EVENT_GEN_KILL_10000ZOMBIES",
	[11]="ACHIEVEMENT_EVENT_GEN_KILL_100000ZOMBIES",
	[12]="ACHIEVEMENT_EVENT_GEN_KILL_100COMBINES",
	[13]="ACHIEVEMENT_EVENT_GEN_KILL_1000COMBINES",
	[14]="ACHIEVEMENT_EVENT_GEN_KILL_10000COMBINES",
	[15]="ACHIEVEMENT_EVENT_GEN_KILL_100000COMBINES",
	[16]="ACHIEVEMENT_EVENT_GEN_KILL_100REBELS",
	[17]="ACHIEVEMENT_EVENT_GEN_KILL_1000REBELS",
	[18]="ACHIEVEMENT_EVENT_GEN_KILL_10000REBELS",
	[19]="ACHIEVEMENT_EVENT_GEN_KILL_100000REBELS",
	[20]="ACHIEVEMENT_EVENT_GEN_KILL_100VORTIGAUNTS",
	[21]="ACHIEVEMENT_EVENT_GEN_KILL_1000VORTIGAUNTS",
	[22]="ACHIEVEMENT_EVENT_GEN_KILL_10000VORTIGAUNTS",
	[23]="ACHIEVEMENT_EVENT_GEN_KILL_100000VORTIGAUNTS",
	[24]="ACHIEVEMENT_EVENT_GEN_KILL_100HEADCRABS",
	[25]="ACHIEVEMENT_EVENT_GEN_KILL_1000HEADCRABS",
	[26]="ACHIEVEMENT_EVENT_GEN_KILL_10000HEADCRABS",
	[27]="ACHIEVEMENT_EVENT_GEN_KILL_100000HEADCRABS",
	
	[28]="ACHIEVEMENT_EVENT_GEN_BEAT_ALLEP3",
	[29]="ACHIEVEMENT_EVENT_GEN_BEAT_ALLCD",
	[30]="ACHIEVEMENT_EVENT_GEN_BEAT_ALLMETA",
	[31]="ACHIEVEMENT_EVENT_GEN_EVENT_EP2_OPEN",
	
	[32]="ACHIEVEMENT_EVENT_GEN_LOOT_100S3",
	[33]="ACHIEVEMENT_EVENT_GEN_LOOT_LEGENDARY",
	[34]="ACHIEVEMENT_EVENT_GEN_LOOT_PLAN",
	
	[35]="ACHIEVEMENT_EVENT_GEN_LOOT_LOOT10",
	[36]="ACHIEVEMENT_EVENT_GEN_LOOT_LOOT100",
	[37]="ACHIEVEMENT_EVENT_GEN_LOOT_LOOT1000",
	[38]="ACHIEVEMENT_EVENT_GEN_LOOT_LOOT100000",
	[39]="ACHIEVEMENT_EVENT_GEN_LOOT_LOOT1000000",
	[40]="ACHIEVEMENT_EVENT_GEN_LOOT_LOOT10000000",
	
	
	-- "ACHIEVEMENT_EVENT_GEN_EVENT_LOVE_4EVER",
	-- "ACHIEVEMENT_EVENT_GEN_EVENT_FIND_EGGS",
	-- "ACHIEVEMENT_EVENT_GEN_EVENT_HALLOWEEN_2016",
	-- "ACHIEVEMENT_EVENT_GEN_KILL_HEADLESS_BOSS",
	-- "ACHIEVEMENT_EVENT_GEN_EVENT_CHRISTMAS_2016",
	-- "ACHIEVEMENT_EVENT_GEN_SAVE_SANTA",
	-- "ACHIEVEMENT_EVENT_GEN_EVENT_NEWYEAR_2017",
	-- "ACHIEVEMENT_EVENT_GEN_EVENT_LOVE_2017",
	-- "ACHIEVEMENT_EVENT_GEN_EVENT_EASTER_2017",

}

Hl2c.GEN_ACH_LIST[#Hl2c.GEN_ACH_LIST+1]="ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM1"
GEN_ACH_LIST_MAT["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM1"]="vgui/achievements/hl2_find_alllambdas"
GEN_ACH_LIST_TITLE["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM1"]="More Mods"
GEN_ACH_LIST_TEXT["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM1"]="Finish 1 custom map"
Hl2c.GEN_ACH_LIST[#Hl2c.GEN_ACH_LIST+1]="ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM10"
GEN_ACH_LIST_MAT["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM10"]="vgui/achievements/hl2_find_alllambdas"
GEN_ACH_LIST_TITLE["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM10"]="More Mods"
GEN_ACH_LIST_TEXT["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM10"]="Finish 10 custom map"
Hl2c.GEN_ACH_LIST[#Hl2c.GEN_ACH_LIST+1]="ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM100"
GEN_ACH_LIST_MAT["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM100"]="vgui/achievements/hl2_find_alllambdas"
GEN_ACH_LIST_TITLE["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM100"]="More Mods"
GEN_ACH_LIST_TEXT["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM100"]="Finish 100 custom map"
Hl2c.GEN_ACH_LIST[#Hl2c.GEN_ACH_LIST+1]="ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM1000"
GEN_ACH_LIST_MAT["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM1000"]="vgui/achievements/hl2_find_alllambdas"
GEN_ACH_LIST_TITLE["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM1000"]="More Mods"
GEN_ACH_LIST_TEXT["ACHIEVEMENT_EVENT_GEN_PLAY_CUSTOM1000"]="Finish 1000 custom map"