if SERVER then AddCSLuaFile() end


// Achievements list of Half-Life 2
HL2_ACH_LIST_MAT = {
	["ACHIEVEMENT_EVENT_HL2_HIT_CANCOP_WITHCAN"] = "vgui/achievements/hl2_hit_cancop_withcan",
	["ACHIEVEMENT_EVENT_HL2_PUT_CANINTRASH"] = "vgui/achievements/hl2_put_canintrash",
	["ACHIEVEMENT_EVENT_HL2_ESCAPE_APARTMENTRAID"] = "vgui/achievements/hl2_escape_apartmentraid",
	["ACHIEVEMENT_EVENT_HL2_BREAK_MINITELEPORTER"] = "vgui/achievements/hl2_break_miniteleporter",
	["ACHIEVEMENT_EVENT_HL2_GET_CROWBAR"] = "vgui/achievements/hl2_get_crowbar",
	["ACHIEVEMENT_EVENT_HL2_GET_AIRBOAT"] =  "vgui/achievements/hl2_get_airboat",
	["ACHIEVEMENT_EVENT_HL2_GET_AIRBOATGUN"] = "vgui/achievements/hl2_get_airboatgun",
	["ACHIEVEMENT_EVENT_HL2_FIND_VORTIGAUNTCAVE"] = "vgui/achievements/hl2_find_vortigauntcave",
	["ACHIEVEMENT_EVENT_HL2_KILL_CHOPPER"] = "vgui/achievements/hl2_kill_chopper",
	["ACHIEVEMENT_EVENT_HL2_FIND_HEVFACEPLATE"] = "vgui/achievements/hl2_find_hevfaceplate",
	["ACHIEVEMENT_EVENT_HL2_GET_GRAVITYGUN"] = "vgui/achievements/hl2_get_gravitygun",
	["ACHIEVEMENT_EVENT_HL2_MAKEABASKET"] = "vgui/achievements/hl2_makeabasket",
	--["ACHIEVEMENT_EVENT_HL2_BEAT_RAVENHOLM_NOWEAPONS_START"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_BEAT_RAVENHOLM_NOWEAPONS_END"] = "vgui/achievements/hl2_beat_ravenholm_noweapons",
	["ACHIEVEMENT_EVENT_HL2_BEAT_CEMETERY"] = "vgui/achievements/hl2_beat_cemetery",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHCRANE"] = "vgui/achievements/hl2_kill_enemies_withcrane",
	["ACHIEVEMENT_EVENT_HL2_PIN_SOLDIER_TOBILLBOARD"] = "vgui/achievements/hl2_pin_soldier_tobillboard",
	["ACHIEVEMENT_EVENT_HL2_KILL_ODESSAGUNSHIP"] = "vgui/achievements/hl2_kill_odessagunship",
	["ACHIEVEMENT_EVENT_HL2_BEAT_DONTTOUCHSAND"] = "vgui/achievements/hl2_beat_donttouchsand",
	--["ACHIEVEMENT_EVENT_HL2_ENTER_NOVAPROSPEKT"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_BEAT_TURRETSTANDOFF2"] = "vgui/achievements/hl2_beat_turretstandoff2",
	["ACHIEVEMENT_EVENT_HL2_FOLLOWFREEMAN"] = "vgui/achievements/hl2_followfreeman",
	["ACHIEVEMENT_EVENT_HL2_BEAT_TOXICTUNNEL"] = "vgui/achievements/hl2_beat_toxictunnel",
	["ACHIEVEMENT_EVENT_HL2_BEAT_PLAZASTANDOFF"] = "vgui/achievements/hl2_beat_plazastandoff",
	["ACHIEVEMENT_EVENT_HL2_KILL_ALLC1709SNIPERS"] = "vgui/achievements/hl2_kill_allc1709snipers",
	["ACHIEVEMENT_EVENT_HL2_BEAT_SUPRESSIONDEVICE"] = "vgui/achievements/hl2_beat_supressiondevice",
	["ACHIEVEMENT_EVENT_HL2_BEAT_C1713STRIDERSTANDOFF"] = "vgui/achievements/hl2_beat_c1713striderstandoff",
	["ACHIEVEMENT_EVENT_HL2_BEAT_GAME"] = "vgui/achievements/hl2_beat_game",
	/*
	["ACHIEVEMENT_EVENT_HL2_GMAN_KLEINERSLAB"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_GMAN_TRAINCAR"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_GMAN_REDBARN"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_GMAN_OUTDOORMONITOR"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_GMAN_CATWALK"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_GMAN_DAM"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_GMAN_TRAINTRACKS"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_GMAN_ODESSA"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_GMAN_PRISONMONITOR"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_GMAN_FOYERTV"] = "vgui/achievements/hl2_find_alllambdas"
	*/
	--["ACHIEVEMENT_EVENT_HL2_FIND_ALLLAMBDAS"] = "vgui/achievements/hl2_find_alllambdas"
	
	
	["ACHIEVEMENT_EVENT_HL2_FIND_ALLLAMBDAS"] = "vgui/achievements/hl2_find_alllambdas",
	["ACHIEVEMENT_EVENT_HL2_KILL_SIXGUNSHIPS"] = "vgui/achievements/hl2_kill_threegunships",
	["ACHIEVEMENT_EVENT_HL2_KILL_BARNACLESWITHBARREL"] = "vgui/achievements/hl2_kill_barnacleswithbarrel",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMY_WITHTOILET"] = "vgui/achievements/hl2_kill_enemy_withtoilet",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHMANHACK"] = "vgui/achievements/hlx_kill_enemies_withmanhack",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHANTLIONS"] = "vgui/achievements/hl2_kill_enemies_withantlions",
	["ACHIEVEMENT_EVENT_HL2_BEAT_GAME_ONLYCROWBAR"] = "vgui/achievements/hl2_get_crowbar",
}

HL2_ACH_LIST_TEXT = {
	["ACHIEVEMENT_EVENT_HL2_HIT_CANCOP_WITHCAN"] = "Hit the trashcan cop with the can.",
	["ACHIEVEMENT_EVENT_HL2_PUT_CANINTRASH"] = "Put the can in the trash.",
	["ACHIEVEMENT_EVENT_HL2_ESCAPE_APARTMENTRAID"] = "Escape the apartment block raid.",
	["ACHIEVEMENT_EVENT_HL2_BREAK_MINITELEPORTER"] = "Break the mini-teleporter in Kleiner's lab.",
	["ACHIEVEMENT_EVENT_HL2_GET_CROWBAR"] = "Get the crowbar.",
	["ACHIEVEMENT_EVENT_HL2_GET_AIRBOAT"] =  "Get the Airboat",
	["ACHIEVEMENT_EVENT_HL2_GET_AIRBOATGUN"] = "Get the airboat's mounted gun.",
	["ACHIEVEMENT_EVENT_HL2_FIND_VORTIGAUNTCAVE"] = "Discover the hidden singing vortigaunt cave in chapter Water Hazard.",
	["ACHIEVEMENT_EVENT_HL2_KILL_CHOPPER"] = "Destroy the hunter-chopper in Half-Life 2.",
	["ACHIEVEMENT_EVENT_HL2_FIND_HEVFACEPLATE"] = "Find the HEV Suit Charger faceplate in Eli's scrapyard.",
	["ACHIEVEMENT_EVENT_HL2_GET_GRAVITYGUN"] = "Get the Gravity Gun in Black Mesa East",
	["ACHIEVEMENT_EVENT_HL2_MAKEABASKET"] = "Make a basket in Eli's scrapyard.",
	--["ACHIEVEMENT_EVENT_HL2_BEAT_RAVENHOLM_NOWEAPONS_START"] = "Beat Ravenholm Gravgun only. (Start).",
	["ACHIEVEMENT_EVENT_HL2_BEAT_RAVENHOLM_NOWEAPONS_END"] = "Play through Ravenholm using only the Gravity Gun.",
	["ACHIEVEMENT_EVENT_HL2_BEAT_CEMETERY"] = "Escort Gregori safely through the church cemetery.",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHCRANE"] = "Kill 3 enemies using the crane.",
	["ACHIEVEMENT_EVENT_HL2_PIN_SOLDIER_TOBILLBOARD"] = "Pin the soldier to the billboard with the crossbow in chapter Highway 17.",
	["ACHIEVEMENT_EVENT_HL2_KILL_ODESSAGUNSHIP"] = "Defend Little Odessa from the gunship attack.",
	["ACHIEVEMENT_EVENT_HL2_BEAT_DONTTOUCHSAND"] = "Cross the antlion beach in chapter Sandtraps without touching the sand.",
	--["ACHIEVEMENT_EVENT_HL2_ENTER_NOVAPROSPEKT"] = "Get inside Nova Prospekt",
	["ACHIEVEMENT_EVENT_HL2_BEAT_TURRETSTANDOFF2"] = "Survive the second turret standoff in the prison.",
	["ACHIEVEMENT_EVENT_HL2_FOLLOWFREEMAN"] = "Gain command of a squad of rebels in the uprising",
	["ACHIEVEMENT_EVENT_HL2_BEAT_TOXICTUNNEL"] = "Get through the toxic tunnel under City 17 in Half-Life 2.",
	["ACHIEVEMENT_EVENT_HL2_BEAT_PLAZASTANDOFF"] = "Survive the Generator Plaza standoff in chapter Anticitizen One.",
	["ACHIEVEMENT_EVENT_HL2_KILL_ALLC1709SNIPERS"] = "Kill all of the snipers in City 17.",
	["ACHIEVEMENT_EVENT_HL2_BEAT_SUPRESSIONDEVICE"] = "Shut down the supression device by disabling its generators.",
	["ACHIEVEMENT_EVENT_HL2_BEAT_C1713STRIDERSTANDOFF"] = "Survive the rooftop strider battle in the ruins of City 17.",
	["ACHIEVEMENT_EVENT_HL2_BEAT_GAME"] = "Destroy the Citadel's reactor core.",
	/*
	["ACHIEVEMENT_EVENT_HL2_GMAN_KLEINERSLAB"] = "G-Man: trainstation_05 on Kleiner's Monitor",
	["ACHIEVEMENT_EVENT_HL2_GMAN_TRAINCAR"] = "G-Man: canals_01 on TV in vort train car",
	["ACHIEVEMENT_EVENT_HL2_GMAN_REDBARN"] = "G-Man: canals_06 at the red barn",
	["ACHIEVEMENT_EVENT_HL2_GMAN_OUTDOORMONITOR"] = "G-Man: canals_06 on giant outdoor monitor",
	["ACHIEVEMENT_EVENT_HL2_GMAN_CATWALK"] = "G-Man: canals_12 on catwalk",
	["ACHIEVEMENT_EVENT_HL2_GMAN_DAM"] = "G-Man: canals_13 to the left of the dam",
	["ACHIEVEMENT_EVENT_HL2_GMAN_TRAINTRACKS"] = "G-Man: town_05 at the end of the tracks",
	["ACHIEVEMENT_EVENT_HL2_GMAN_ODESSA"] = "G-Man: coast_03 odessa meeting",
	["ACHIEVEMENT_EVENT_HL2_GMAN_PRISONMONITOR"] = "G-Man: prison_02 control room monitor",
	["ACHIEVEMENT_EVENT_HL2_GMAN_FOYERTV"] = "G-Man: c17_02 on TV in the destroyed foyer"
	*/
	--["ACHIEVEMENT_EVENT_HL2_FIND_ALLLAMBDAS"] = "Find all hidden lamda symbols."
	
	["ACHIEVEMENT_EVENT_HL2_FIND_ALLLAMBDAS"] = "Find all hidden lamda symbols.",
	["ACHIEVEMENT_EVENT_HL2_KILL_SIXGUNSHIPS"] = "Destroy six gunships in Half-Life 2.",
	["ACHIEVEMENT_EVENT_HL2_KILL_BARNACLESWITHBARREL"] = "Kill five barnacles with one barrel.",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMY_WITHTOILET"] = "Kill an enemy with a toilet.",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHMANHACK"] = "Kill five enemies with a manhack.",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHANTLIONS"] = "Use the antlions to kill 50 enemies.",
	["ACHIEVEMENT_EVENT_HL2_BEAT_GAME_ONLYCROWBAR"] = "Beat the game only using a crowbar.",
}

HL2_ACH_LIST_TITLE = {
	["ACHIEVEMENT_EVENT_HL2_HIT_CANCOP_WITHCAN"] = "Defiant",
	["ACHIEVEMENT_EVENT_HL2_PUT_CANINTRASH"] = "Submissive",
	["ACHIEVEMENT_EVENT_HL2_ESCAPE_APARTMENTRAID"] = "Malcontent",
	["ACHIEVEMENT_EVENT_HL2_BREAK_MINITELEPORTER"] = "What cat?",
	["ACHIEVEMENT_EVENT_HL2_GET_CROWBAR"] = "Trusty Hardware",
	["ACHIEVEMENT_EVENT_HL2_GET_AIRBOAT"] =  "Anchor's Aweigh!",
	["ACHIEVEMENT_EVENT_HL2_GET_AIRBOATGUN"] = "Heavy Weapons",
	["ACHIEVEMENT_EVENT_HL2_FIND_VORTIGAUNTCAVE"] = "Vorticough",
	["ACHIEVEMENT_EVENT_HL2_KILL_CHOPPER"] = "Revenge!",
	["ACHIEVEMENT_EVENT_HL2_FIND_HEVFACEPLATE"] = "Blast from the Past",
	["ACHIEVEMENT_EVENT_HL2_GET_GRAVITYGUN"] = "Zero-Point Energy",
	["ACHIEVEMENT_EVENT_HL2_MAKEABASKET"] = "Two Points",
	--["ACHIEVEMENT_EVENT_HL2_BEAT_RAVENHOLM_NOWEAPONS_START"] = "Beat Ravenholm Gravgun only. (Start).",
	["ACHIEVEMENT_EVENT_HL2_BEAT_RAVENHOLM_NOWEAPONS_END"] = "Zombie Chopper",
	["ACHIEVEMENT_EVENT_HL2_BEAT_CEMETERY"] = "Hallowed Ground",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHCRANE"] = "OSHA Violation",
	["ACHIEVEMENT_EVENT_HL2_PIN_SOLDIER_TOBILLBOARD"] = "Targetted Advertising",
	["ACHIEVEMENT_EVENT_HL2_KILL_ODESSAGUNSHIP"] = "Where Cubbage Fears to Tread",
	["ACHIEVEMENT_EVENT_HL2_BEAT_DONTTOUCHSAND"] = "Keep Off the Sand!",
	--["ACHIEVEMENT_EVENT_HL2_ENTER_NOVAPROSPEKT"] = "Get inside Nova Prospekt",
	["ACHIEVEMENT_EVENT_HL2_BEAT_TURRETSTANDOFF2"] = "Warden Freeman",
	["ACHIEVEMENT_EVENT_HL2_FOLLOWFREEMAN"] = "Follow Freeman",
	["ACHIEVEMENT_EVENT_HL2_BEAT_TOXICTUNNEL"] = "Radiation Levels Detected",
	["ACHIEVEMENT_EVENT_HL2_BEAT_PLAZASTANDOFF"] = "Plaza Defender",
	["ACHIEVEMENT_EVENT_HL2_KILL_ALLC1709SNIPERS"] = "Counter-Sniper",
	["ACHIEVEMENT_EVENT_HL2_BEAT_SUPRESSIONDEVICE"] = "Fight the Power",
	["ACHIEVEMENT_EVENT_HL2_BEAT_C1713STRIDERSTANDOFF"] = "Giant Killer",
	["ACHIEVEMENT_EVENT_HL2_BEAT_GAME"] = "Singularity Collapse",
	/*
	["ACHIEVEMENT_EVENT_HL2_GMAN_KLEINERSLAB"] = "G-Man: trainstation_05 on Kleiner's Monitor",
	["ACHIEVEMENT_EVENT_HL2_GMAN_TRAINCAR"] = "G-Man: canals_01 on TV in vort train car",
	["ACHIEVEMENT_EVENT_HL2_GMAN_REDBARN"] = "G-Man: canals_06 at the red barn",
	["ACHIEVEMENT_EVENT_HL2_GMAN_OUTDOORMONITOR"] = "G-Man: canals_06 on giant outdoor monitor",
	["ACHIEVEMENT_EVENT_HL2_GMAN_CATWALK"] = "G-Man: canals_12 on catwalk",
	["ACHIEVEMENT_EVENT_HL2_GMAN_DAM"] = "G-Man: canals_13 to the left of the dam",
	["ACHIEVEMENT_EVENT_HL2_GMAN_TRAINTRACKS"] = "G-Man: town_05 at the end of the tracks",
	["ACHIEVEMENT_EVENT_HL2_GMAN_ODESSA"] = "G-Man: coast_03 odessa meeting",
	["ACHIEVEMENT_EVENT_HL2_GMAN_PRISONMONITOR"] = "G-Man: prison_02 control room monitor",
	["ACHIEVEMENT_EVENT_HL2_GMAN_FOYERTV"] = "G-Man: c17_02 on TV in the destroyed foyer"
	*/
	
	--["ACHIEVEMENT_EVENT_HL2_FIND_ALLLAMBDAS"] = "Find all hidden lamda symbols."
	
	["ACHIEVEMENT_EVENT_HL2_FIND_ALLLAMBDAS"] = "Lambda Locator",
	["ACHIEVEMENT_EVENT_HL2_KILL_SIXGUNSHIPS"] = "One Man Army",
	["ACHIEVEMENT_EVENT_HL2_KILL_BARNACLESWITHBARREL"] = "Barnacle Bowling",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMY_WITHTOILET"] = "Flushed",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHMANHACK"] = "Hack Attack!",
	["ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHANTLIONS"] = "Bug Hunt",
	["ACHIEVEMENT_EVENT_HL2_BEAT_GAME_ONLYCROWBAR"] = "The True One Freeman",
}

HL2_ACH_LIST = {
	"ACHIEVEMENT_EVENT_HL2_HIT_CANCOP_WITHCAN",
	"ACHIEVEMENT_EVENT_HL2_PUT_CANINTRASH",
	"ACHIEVEMENT_EVENT_HL2_ESCAPE_APARTMENTRAID",
	"ACHIEVEMENT_EVENT_HL2_BREAK_MINITELEPORTER",
	"ACHIEVEMENT_EVENT_HL2_GET_CROWBAR",
	"ACHIEVEMENT_EVENT_HL2_GET_AIRBOAT",
	"ACHIEVEMENT_EVENT_HL2_GET_AIRBOATGUN",
	"ACHIEVEMENT_EVENT_HL2_FIND_VORTIGAUNTCAVE",
	"ACHIEVEMENT_EVENT_HL2_KILL_CHOPPER",
	"ACHIEVEMENT_EVENT_HL2_FIND_HEVFACEPLATE",
	"ACHIEVEMENT_EVENT_HL2_GET_GRAVITYGUN",
	"ACHIEVEMENT_EVENT_HL2_MAKEABASKET",
	--"ACHIEVEMENT_EVENT_HL2_BEAT_RAVENHOLM_NOWEAPONS_START",
	"ACHIEVEMENT_EVENT_HL2_BEAT_RAVENHOLM_NOWEAPONS_END",
	"ACHIEVEMENT_EVENT_HL2_BEAT_CEMETERY",
	"ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHCRANE",
	"ACHIEVEMENT_EVENT_HL2_PIN_SOLDIER_TOBILLBOARD",
	"ACHIEVEMENT_EVENT_HL2_KILL_ODESSAGUNSHIP",
	"ACHIEVEMENT_EVENT_HL2_BEAT_DONTTOUCHSAND",
	--"ACHIEVEMENT_EVENT_HL2_ENTER_NOVAPROSPEKT",
	"ACHIEVEMENT_EVENT_HL2_BEAT_TURRETSTANDOFF2",
	"ACHIEVEMENT_EVENT_HL2_FOLLOWFREEMAN",
	"ACHIEVEMENT_EVENT_HL2_BEAT_TOXICTUNNEL",
	"ACHIEVEMENT_EVENT_HL2_BEAT_PLAZASTANDOFF",
	"ACHIEVEMENT_EVENT_HL2_KILL_ALLC1709SNIPERS",
	"ACHIEVEMENT_EVENT_HL2_BEAT_SUPRESSIONDEVICE",
	"ACHIEVEMENT_EVENT_HL2_BEAT_C1713STRIDERSTANDOFF",
	"ACHIEVEMENT_EVENT_HL2_BEAT_GAME",
	/*
	"ACHIEVEMENT_EVENT_HL2_BEAT_GAME",
	"ACHIEVEMENT_EVENT_HL2_GMAN_KLEINERSLAB",
	"ACHIEVEMENT_EVENT_HL2_GMAN_TRAINCAR",
	"ACHIEVEMENT_EVENT_HL2_GMAN_REDBARN",
	"ACHIEVEMENT_EVENT_HL2_GMAN_OUTDOORMONITOR",
	"ACHIEVEMENT_EVENT_HL2_GMAN_CATWALK",
	"ACHIEVEMENT_EVENT_HL2_GMAN_DAM",
	"ACHIEVEMENT_EVENT_HL2_GMAN_TRAINTRACKS",
	"ACHIEVEMENT_EVENT_HL2_GMAN_ODESSA",
	"ACHIEVEMENT_EVENT_HL2_GMAN_PRISONMONITOR",
	"ACHIEVEMENT_EVENT_HL2_GMAN_FOYERTV"
	*/
	
	--"ACHIEVEMENT_EVENT_HL2_FIND_ALLLAMBDAS" = "Find all hidden lamda symbols."
	
	"ACHIEVEMENT_EVENT_HL2_FIND_ALLLAMBDAS",
	"ACHIEVEMENT_EVENT_HL2_KILL_SIXGUNSHIPS",
	"ACHIEVEMENT_EVENT_HL2_KILL_BARNACLESWITHBARREL",
	"ACHIEVEMENT_EVENT_HL2_KILL_ENEMY_WITHTOILET",
	"ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHMANHACK",
	"ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHANTLIONS",
	"ACHIEVEMENT_EVENT_HL2_BEAT_GAME_ONLYCROWBAR",
}


-- PART TWO HALF-LIFE 2 ACHIEVEMENTS

HL2_P2_ACH_LIST = {
	

}

HL2_P2_ACH_LIST_TITLE = {
	

}

HL2_P2_ACH_LIST_TEXT = {
	

}

HL2_P2_ACH_LIST_MAT = {
	
}







Hl2c.HL2_ACH_LIST = {
	[1] = "ACHIEVEMENT_EVENT_HL2_HIT_CANCOP_WITHCAN",
	[2] = "ACHIEVEMENT_EVENT_HL2_PUT_CANINTRASH",
	[3] = "ACHIEVEMENT_EVENT_HL2_ESCAPE_APARTMENTRAID",
	[4] = "ACHIEVEMENT_EVENT_HL2_BREAK_MINITELEPORTER",
	[5] = "ACHIEVEMENT_EVENT_HL2_GET_CROWBAR",
	[6] = "ACHIEVEMENT_EVENT_HL2_GET_AIRBOAT",
	[7] = "ACHIEVEMENT_EVENT_HL2_GET_AIRBOATGUN",
	[8] = "ACHIEVEMENT_EVENT_HL2_FIND_VORTIGAUNTCAVE",
	[9] = "ACHIEVEMENT_EVENT_HL2_KILL_CHOPPER",
	[10] = "ACHIEVEMENT_EVENT_HL2_FIND_HEVFACEPLATE",
	[11] = "ACHIEVEMENT_EVENT_HL2_GET_GRAVITYGUN",
	[12] = "ACHIEVEMENT_EVENT_HL2_MAKEABASKET",
	
	[13] = "ACHIEVEMENT_EVENT_HL2_BEAT_RAVENHOLM_NOWEAPONS_END",
	[14] = "ACHIEVEMENT_EVENT_HL2_BEAT_CEMETERY",
	[15] = "ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHCRANE",
	[16] = "ACHIEVEMENT_EVENT_HL2_PIN_SOLDIER_TOBILLBOARD",
	[17] = "ACHIEVEMENT_EVENT_HL2_KILL_ODESSAGUNSHIP",
	[18] = "ACHIEVEMENT_EVENT_HL2_BEAT_DONTTOUCHSAND",
	
	[19] = "ACHIEVEMENT_EVENT_HL2_BEAT_TURRETSTANDOFF2",
	[20] = "ACHIEVEMENT_EVENT_HL2_FOLLOWFREEMAN",
	[21] = "ACHIEVEMENT_EVENT_HL2_BEAT_TOXICTUNNEL",
	[22] = "ACHIEVEMENT_EVENT_HL2_BEAT_PLAZASTANDOFF",
	[23] = "ACHIEVEMENT_EVENT_HL2_KILL_ALLC1709SNIPERS",
	[24] = "ACHIEVEMENT_EVENT_HL2_BEAT_SUPRESSIONDEVICE",
	[25] = "ACHIEVEMENT_EVENT_HL2_BEAT_C1713STRIDERSTANDOFF",
	[26] = "ACHIEVEMENT_EVENT_HL2_BEAT_GAME",

	[27] = "ACHIEVEMENT_EVENT_HL2_FIND_ALLLAMBDAS",
	[28] = "ACHIEVEMENT_EVENT_HL2_KILL_SIXGUNSHIPS",
	[29] = "ACHIEVEMENT_EVENT_HL2_KILL_BARNACLESWITHBARREL",
	[30] = "ACHIEVEMENT_EVENT_HL2_KILL_ENEMY_WITHTOILET",
	[31] = "ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHMANHACK",
	[32] = "ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHANTLIONS",
	[33] = "ACHIEVEMENT_EVENT_HL2_BEAT_GAME_ONLYCROWBAR", 
}