if SERVER then AddCSLuaFile() end

NPC_COUNT_KILLS = {
	["npc_antlion"] = {true,"COUNT_KILLS_ANTLIONS"},
	["npc_antlionguard"] = {true,"COUNT_KILLS_ANTLIONS"},
	["npc_zombine"] = {true,"COUNT_KILLS_ZOMBIES"},
	["npc_zombie"] = {true,"COUNT_KILLS_ZOMBIES"},
	["npc_fastzombie"] = {true,"COUNT_KILLS_ZOMBIES"},
	["npc_poisonzombie"] = {true,"COUNT_KILLS_ZOMBIES"},
	["npc_zombie_torso"] = {true,"COUNT_KILLS_ZOMBIES"},
	["npc_combine_s"] = {true,"COUNT_KILLS_COMBINES"},
	["npc_rollermine"] = {true,"COUNT_KILLS_COMBINES"},
	["npc_manhack"] = {true,"COUNT_KILLS_COMBINES"},
	["npc_hunter"] = {true,"COUNT_KILLS_COMBINES"},
	["npc_cscanner"] = {true,"COUNT_KILLS_COMBINES"},
	["npc_metropolice"] = {true,"COUNT_KILLS_COMBINES"},
	["npc_turret_ceiling"] = {true,"COUNT_KILLS_COMBINES"},
	["npc_turret_ground"] = {true,"COUNT_KILLS_COMBINES"},
	["npc_strider"] = {true,"COUNT_KILLS_COMBINES"},
	["npc_citizen"] = {true,"COUNT_KILLS_REBELS"},
	["npc_vortigaunt"] = {true,"COUNT_KILLS_VORTIGAUNTS"},
	["npc_headcrab"] = {true,"COUNT_KILLS_HEADCRABS"},
	["npc_headcrab_fast"] = {true,"COUNT_KILLS_HEADCRABS"},
	["npc_headcrab_black"] = {true,"COUNT_KILLS_HEADCRABS"},
	["npc_headcrab_poison"] = {true,"COUNT_KILLS_HEADCRABS"},
}

NPC_SHOULD_GIVE_POINTS = {
	["npc_hunter"] = {true,1},
	["npc_combinegunship"] = {true,1},
	["npc_helicopter"] = {true,1},
	["npc_cremator"] = {true,2},
	-- ["npc_combinedropship"] = {true,3},
	["npc_antlionguard"] = {true,1},
	["npc_turret_ceiling"] = {true,1},
	["npc_turret_ground"] = {true,1},
	["npc_barnacle"] = {true,1},
	["npc_strider"] = {true,1},
	["prop_vehicle_apc"] = {true,1},
	["npc_apcdriver"] = {true,1},
	-- ["npc_fassassin"] = {true,1}
}

// Should Give Points Values with keys
NPC_SHOULD_GIVE_POINT_VALUES = {
	["npc_hunter"] = 1,
	["npc_combinegunship"] = 1,
	["npc_helicopter"] = 1,
	["npc_cremator"] = 2,
	-- ["npc_combinedropship"] = 3,
	["npc_antlionguard"] = 1,
	["npc_turret_ceiling"] = 1,
	["npc_turret_ground"] = 1,
	["npc_barnacle"] = 1,
	["prop_vehicle_apc"] = 1,
	["npc_apcdriver"] = 1,
	-- ["npc_fassassin"] = 1
}
//Should Give Point Npcs Name
NPC_SHOULD_GIVE_POINT = {
	"npc_hunter",
	"npc_combinegunship",
	"npc_helicopter",
	"npc_cremator",
	-- "npc_combinedropship",
	"npc_antlionguard",
	"npc_turret_ceiling",
	"npc_turret_ground",
	"npc_barnacle",
	"prop_vehicle_apc",
	"npc_apcdriver",
	-- "npc_fassassin"
}

// Points to give a player for killing an NPC (if non-one)
NPC_POINT_VALUES = {
	["npc_antlion"] = 1,
	["npc_fassassin"] = 2,
	["npc_hunter"] = 3,
	["npc_cremator"] = 2,
	["npc_apcdriver"] = 2,
	["prop_vehicle_apc"] = 2,
	["npc_barnacle"] = 1,
	["npc_antlionguard"] = 4,
	["npc_sniper"] = 4,
	["npc_citizen"] = 1,
	["npc_cscanner"] = 1,
	["npc_crabsynth"] = 1,
	["npc_stalker"] = 1,
	["npc_crow"] = 1,
	["npc_ministrider"] = 2,
	["npc_pigeon"] = 1,
	["npc_strider"] = 10,
	["npc_metropolice"] = 1,
	["npc_combine_s"] = 1,
	["npc_manhack"] = 1,
	["npc_turret_ceiling"] = 1,
	--["npc_turret_floor"] = 3,
	["npc_turret_ground"] = 1,
	["npc_zombie"] = 1,
	["npc_poisonzombie"] = 2,
	["npc_zombine"] = 1,
	["npc_fastzombie"] = 1,
	["npc_fastzombie_torso"] = 1,
	["npc_zombie_torso"] = 1,
	["npc_headcrab"] = 1,
	["npc_headcrab_fast"] = 1,
	["npc_headcrab_black"] = 1,
	["npc_headcrab_poison"] = 1
}
NPC_POINTS_VALUES = {
	["npc_antlion"] = {true,1},
	["npc_combinegunship"] = {true,5},
	["npc_fassassin"] = {true,2},
	["npc_hunter"] = {true,2},
	["npc_cremator"] = {true,2},
	["npc_apcdriver"] = {true,2},
	["prop_vehicle_apc"] = {true,2},
	["npc_barnacle"] = {true,1},
	["npc_antlionguard"] = {true,5},
	["npc_sniper"] = {true,1},
	["npc_citizen"] = {true,1},
	["npc_cscanner"] = {true,1},
	["npc_crabsynth"] = {true,1},
	["npc_stalker"] = {true,1},
	["npc_helicopter"] = {true,5},
	["npc_crow"] = {true,1},
	["npc_ministrider"] = {true,1},
	["npc_pigeon"] = {true,1},
	["npc_strider"] = {true,5},
	["npc_metropolice"] = {true,1},
	["npc_combine_s"] = {true,1},
	["npc_manhack"] = {true,1},
	-- ["npc_strider"] = {true,11},
	["npc_turret_ceiling"] = {true,1},
	--["npc_turret_floor"] = {true,3},
	["npc_turret_ground"] = {true,1},
	["npc_zombie"] = {true,1},
	["npc_poisonzombie"] = {true,2},
	["npc_zombine"] = {true,2},
	["npc_fastzombie"] = {true,2},
	["npc_fastzombie_torso"] = {true,2},
	["npc_zombie_torso"] = {true,2},
	["npc_headcrab"] = {true,1},
	["npc_headcrab_fast"] = {true,2},
	["npc_headcrab_black"] = {true,2},
	["npc_headcrab_poison"] = {true,2}
}
