if SERVER then AddCSLuaFile() end

//Targetable NPC ID table
NPC_ID_TARGET = {
	["player"] = true,
	["npc_alyx"] = true,
	["npc_antlion"] = true,
	["npc_barney"] = true,
	["npc_breen"] = true,
	["npc_cremator"] = true,
	["npc_citizen"] = true,
	["npc_combine_s"] = true,
	["npc_cscanner"] = true,
	["npc_dog"] = true,
	["npc_eli"] = true,
	["npc_fassassin"] = true,
	["npc_fastzombie"] = true,
	["npc_fastzombie_torso"] = true,
	["npc_fisherman"] = true,
	["npc_headcrab"] = true,
	["npc_headcrab_black"] = true,
	["npc_headcrab_fast"] = true,
	["npc_headcrab_poison"] = true,
	["npc_hunter"] = true,
	["npc_kleiner"] = true,
	["npc_manhack"] = true,
	["npc_magnusson"] = true,
	["npc_metropolice"] = true,
	["npc_monk"] = true,
	["npc_mossman"] = true,
	["npc_poisonzombie"] = true,
	["npc_rollermine"] = true,
	["npc_stalker"] = true,
	["npc_turret_floor"] = true,
	["npc_vortigaunt"] = true,
	["npc_zombie"] = true,
	["npc_zombie_torso"] = true,
	["npc_zombine"] = true,
	["monster_alien_controller"] = true,
	["monster_alien_grunt"] = true,
	["monster_alien_slave"] = true,
	["monster_babycrab"] = true,
	["monster_barney"] = true,
	["monster_bullchicken"] = true,
	["monster_headcrab"] = true,
	["monster_houndeye"] = true,
	["monster_human_assassin"] = true,
	["monster_human_grunt"] = true,
	["monster_turret"] = true,
	["monster_zombie"] = true,
}

//TARGET BAR NPC LIST table
TARGETBAR_NPC_LIST = {
	["npc_antlionguard"] = true,
	["npc_hunter"] = true,
	["npc_helicopter"] = true,
	["npc_combinegunship"] = true,
	["npc_strider"] = true,
	["monster_gargantua"] = true,
	["monster_bigmomma"] = true,
	["monster_nihilanth"] = true,
}
